# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: aloc

before:
  hooks:
    - go mod tidy

builds:
  - id: aloc
    main: ./cmd/aloc
    binary: aloc
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.buildTime={{.Date}}

archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

brews:
  - repository:
      owner: modern-tooling
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: https://github.com/modern-tooling/aloc
    description: Semantic LOC counter - understand your codebase by role
    license: MIT
    skip_upload: auto
    test: |
      system "#{bin}/aloc", "--help"

# Uncomment to enable Docker releases
# dockers:
#   - image_templates:
#       - "ghcr.io/rgehrsern/aloc:{{ .Tag }}"
#       - "ghcr.io/rgehrsern/aloc:latest"
#     dockerfile: Dockerfile
#     build_flag_templates:
#       - "--label=org.opencontainers.image.created={{.Date}}"
#       - "--label=org.opencontainers.image.title={{.ProjectName}}"
#       - "--label=org.opencontainers.image.revision={{.FullCommit}}"
#       - "--label=org.opencontainers.image.version={{.Version}}"
